version: "3.4"
services:
  backend:
    image: homeless-backend
    container_name: homeless-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_HOST=homeless-mongodb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_URI=$DB_URI
    networks:
    - homeless-network
    env_file:
      - .env

  mongodb:
    image: mongo:5.0.2
    container_name: homeless-mongodb
    command: ["--bind_ip_all"]
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
      - ./entrypoint.js/:/docker-entrypoint-initdb.d/entrypoint.js
    networks:
      - homeless-network
      - homeless-bridge
    env_file:
      - .env

  mongo-seed:
    build: ./seeds
    depends_on:
      - mongodb
    networks:
      - homeless-network
      - homeless-bridge
    environment:
      - DB_URI=$DB_URI

volumes:
  mongodb_data_container:

networks:
  homeless-network:
    external: true
  homeless-bridge:
    name: homeless-bridge
    driver: bridge
